// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64     `json:"id"`
	Account   int64     `json:"account"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID          int64     `json:"id"`
	FromAccount int64     `json:"from_account"`
	ToAccount   int64     `json:"to_account"`
	Amount      int64     `json:"amount"`
	CreatedAt   time.Time `json:"created_at"`
}
